#!/bin/sh
set -e
if [ "x$SSH_ORIGINAL_COMMAND" != "x" ]; then
exec '/srv/conda/envs/notebook/share/git-annex-8.20210903-0/runshell' git-annex-shell -c "$SSH_ORIGINAL_COMMAND"
else
exec '/srv/conda/envs/notebook/share/git-annex-8.20210903-0/runshell' git-annex-shell -c "$@"
fi
